-- Applied by OptimizePublicReadQueries. Forum tables are excluded from EF table DDL.
-- SearchDocument indexes are generated by EF from SearchDocumentEntityConfiguration:
-- IX_SearchDocument_CandidateMetadata (Id) INCLUDE (ContentType, PublishedAt, SourceKey)
-- IX_SearchDocument_ContentType_PublishedAt (ContentType, PublishedAt DESC) INCLUDE (SourceKey)
-- Do not include BodyHtml, SignatureHtml, or search Body in covering indexes.
-- SQL Express mirror comparison, 2026-10-01 (all DDL rolled back):
-- Existing visible discussion starter: ModernForumPost logical reads 145710 -> 3.
-- Global recent 15 threads: ModernForumThread logical reads 1908 -> 3; same result checksum.
-- Queen, 1000 search candidates: SearchDocument logical reads 3071 -> 1006.
-- Queen filtered to news: SearchDocument logical reads 1111 -> 25; 22 candidates both times.
-- Visible forum page 20 ID selection: ModernForumPost logical reads 1642 -> 7; same 20 IDs.
-- These are per-table logical reads, not total FTS reads or production latency promises.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'dbo.ModernForumPost', N'U') IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ModernForumPost') AND name = N'IX_ModernForumPost_VisibleDiscussion')
        CREATE INDEX IX_ModernForumPost_VisibleDiscussion
            ON dbo.ModernForumPost (LegacyThreadTopicId, PostedAt, LegacyPostId)
            WHERE IsHidden = 0;

    IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ModernForumPost') AND name = N'IX_ModernForumPost_Thread_Posted')
        CREATE INDEX IX_ModernForumPost_Thread_Posted
            ON dbo.ModernForumPost (ThreadId, LegacyPostId)
            INCLUDE (PostedAt, AuthorDisplayName, IsHidden)
            WITH (DROP_EXISTING = ON);
    ELSE
        CREATE INDEX IX_ModernForumPost_Thread_Posted
            ON dbo.ModernForumPost (ThreadId, LegacyPostId)
            INCLUDE (PostedAt, AuthorDisplayName, IsHidden);
END;

IF OBJECT_ID(N'dbo.ModernForumThread', N'U') IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.ModernForumThread') AND name = N'IX_ModernForumThread_PublicRecent')
    CREATE INDEX IX_ModernForumThread_PublicRecent
        ON dbo.ModernForumThread (LastActivityAt DESC, LegacyTopicId DESC)
        INCLUDE (CategoryId, Title, ReplyCount)
        WHERE IsHidden = 0 AND IsLegacyTopicStarter = 1 AND StartedByUserValidated = 1;
GO
