using System.Text.RegularExpressions;
using Microsoft.Extensions.Logging;
using QueenZone.Data;
using QueenZone.Storage;
using QueenZone.Web.Search;

namespace QueenZone.Web;

public enum ForumWriteStatus
{
    Success,
    CategoryNotFound,
    TopicNotFound,
    TopicLocked,
    ValidationFailed,
    RateLimited,
    AttachmentFailed,
    MemberSuspended,
}

public sealed record NewForumTopicRequest(
    Guid MemberId,
    string? IdentityName,
    int CategoryId,
    string? Subject,
    string? Body,
    IReadOnlyList<IFormFile>? Attachments,
    NewForumPoll? Poll)
{
    public bool TrustedSystemAuthor { get; init; }
}

public sealed record ForumWriteFieldError(string Field, string Message);

public sealed class ForumWriteOutcome
{
    public bool Succeeded => Status == ForumWriteStatus.Success;

    public ForumWriteStatus Status { get; init; }

    public int TopicId { get; init; }

    public int PostId { get; init; }

    public string Title { get; init; } = string.Empty;

    public string SanitizedBody { get; init; } = string.Empty;

    public IReadOnlyList<ForumWriteFieldError> FieldErrors { get; init; } = [];

    public static ForumWriteOutcome Fail(ForumWriteStatus status, string sanitizedBody = "") =>
        new() { Status = status, SanitizedBody = sanitizedBody };

    public static ForumWriteOutcome Validation(
        string sanitizedBody,
        IReadOnlyList<ForumWriteFieldError> errors) =>
        new()
        {
            Status = ForumWriteStatus.ValidationFailed,
            SanitizedBody = sanitizedBody,
            FieldErrors = errors,
        };

    public static ForumWriteOutcome AttachmentFailed(string sanitizedBody, string message) =>
        new()
        {
            Status = ForumWriteStatus.AttachmentFailed,
            SanitizedBody = sanitizedBody,
            FieldErrors = [new ForumWriteFieldError("Attachments", message)],
        };

    public static ForumWriteOutcome Created(
        int topicId,
        int postId,
        string sanitizedBody,
        string title) =>
        new()
        {
            Status = ForumWriteStatus.Success,
            TopicId = topicId,
            PostId = postId,
            SanitizedBody = sanitizedBody,
            Title = title,
        };
}

/// <summary>
/// Shared create-topic and reply pipeline used by Razor Pages and
/// <c>/api/v1/forum</c> writes so mobile posts hit the same sanitization,
/// attachment rules, and <see cref="ForumPostRateLimiter"/> as the website.
/// </summary>
public sealed class ForumPostWriteService(
    IForumRepository forumRepository,
    IForumWriteRepository forumWriteRepository,
    ForumPostRateLimiter rateLimiter,
    ForumPostContentService contentService,
    ForumPostWriteEffects writeEffects,
    ForumPostModerationService moderationService,
    TimeProvider timeProvider)
{
    public const int SubjectMinLength = 5;

    public const int SubjectMaxLength = 200;

    public const string BodyRequiredMessage = "Body is required.";

    public const string SubjectLengthMessage = "Title must be between 5 and 200 characters.";

    public const string TopicLockedMessage = "This topic is locked.";

    public const string RateLimitedMessage =
        "You're posting too quickly. Please wait a bit and try again.";

    public const string SuspendedMessage = "This account cannot post.";

    /// <summary>
    /// Admin-panel identity recorded on auto-suspensions from <see cref="FlagIfLikelySpamAsync"/>,
    /// so they're distinguishable from a human moderator's action in the audit trail.
    /// </summary>
    public const string AutoModeratorEmail = "automod@queenzone.internal";

    /// <summary>
    /// A post containing a link, made this soon after account creation, is treated as an
    /// automation signature (observed spam accounts post within ~2s of registering) rather
    /// than something a human could plausibly type. Both conditions must hold — link alone,
    /// or speed alone, is too noisy and would catch genuine members. A registration email
    /// matching <see cref="AutoGeneratedFreemailPattern"/> is treated as an equally strong
    /// signal on its own (see <see cref="FlagIfLikelySpamAsync"/>), since that shape is not
    /// something a human picks for their own address.
    /// </summary>
    internal static readonly TimeSpan SpamCandidateWindow = TimeSpan.FromSeconds(60);

    /// <summary>
    /// Matches bulk-signup-generator addresses shaped like
    /// <c>outlook_D2B04D13FE864466@outlook.com</c> — a short word, an underscore, a long hex
    /// run, on a Microsoft freemail domain. Deliberately narrow (this exact shape only) to
    /// keep false positives on genuine, merely-unusual addresses at zero.
    /// </summary>
    internal static readonly Regex AutoGeneratedFreemailPattern = new(
        @"^[a-z]+_[0-9a-f]{12,20}@(outlook|hotmail|live|msn)\.com$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled,
        RegexDefaults.MatchTimeout);

    public async Task<ForumWriteOutcome> CreateTopicAsync(
        NewForumTopicRequest request,
        CancellationToken cancellationToken = default)
    {
        var memberId = request.MemberId;
        var identityName = request.IdentityName;
        var categoryId = request.CategoryId;
        var subject = request.Subject;
        var body = request.Body;
        var attachments = request.Attachments;
        var poll = request.Poll;
        var trustedSystemAuthor = request.TrustedSystemAuthor;

        var category = await forumRepository.GetCategoryByIdAsync(categoryId, cancellationToken);
        if (category is null)
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.CategoryNotFound);
        }

        var author = await moderationService.ResolveAuthorAsync(memberId, identityName, cancellationToken);
        if (author.Status != ForumWriteStatus.Success)
        {
            return ForumWriteOutcome.Fail(author.Status);
        }

        var trimmedSubject = subject?.Trim() ?? string.Empty;
        var fieldErrors = new List<ForumWriteFieldError>();
        if (trimmedSubject.Length < SubjectMinLength || trimmedSubject.Length > SubjectMaxLength)
        {
            fieldErrors.Add(new ForumWriteFieldError("Subject", SubjectLengthMessage));
        }

        var sanitizedBody = contentService.NormalizeForStorage(body);
        if (string.IsNullOrWhiteSpace(sanitizedBody))
        {
            fieldErrors.Add(new ForumWriteFieldError("Body", BodyRequiredMessage));
        }

        var attachmentValidation = contentService.ValidateAttachments(attachments);
        foreach (var error in attachmentValidation.Errors)
        {
            fieldErrors.Add(new ForumWriteFieldError("Attachments", error));
        }

        if (fieldErrors.Count > 0)
        {
            return ForumWriteOutcome.Validation(sanitizedBody, fieldErrors);
        }

        if (!trustedSystemAuthor && !await rateLimiter.IsAllowedAsync(memberId, cancellationToken))
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.RateLimited, sanitizedBody);
        }

        try
        {
            var createdAt = timeProvider.GetUtcNow();
            var created = await forumWriteRepository.CreateThreadAsync(
                new NewForumThread(
                    category.Id,
                    memberId,
                    author.DisplayName,
                    trimmedSubject,
                    sanitizedBody,
                    createdAt,
                    poll),
                cancellationToken);
            await writeEffects.UpsertThreadAsync(
                created.TopicId,
                trimmedSubject,
                createdAt,
                cancellationToken);
            await contentService.UploadAttachmentsAsync(
                created.StarterPostId,
                memberId,
                attachmentValidation.AcceptedFiles,
                cancellationToken);
            writeEffects.InvalidateForumStatsCache();
            if (!trustedSystemAuthor)
            {
                await FlagIfLikelySpamAsync(
                    memberId, author.AccountCreatedAt, author.Email, createdAt, sanitizedBody, cancellationToken);
            }

            return ForumWriteOutcome.Created(
                created.TopicId,
                created.StarterPostId,
                sanitizedBody,
                trimmedSubject);
        }
        catch (NotSupportedException ex)
        {
            return ForumWriteOutcome.AttachmentFailed(sanitizedBody, ex.Message);
        }
        catch (BlobUploadException ex)
        {
            return ForumWriteOutcome.AttachmentFailed(sanitizedBody, ex.Message);
        }
        catch (InvalidOperationException)
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.CategoryNotFound, sanitizedBody);
        }
    }

    public async Task<ForumWriteOutcome> CreateReplyAsync(
        Guid memberId,
        string? identityName,
        int topicId,
        string? body,
        IReadOnlyList<IFormFile>? attachments,
        CancellationToken cancellationToken = default)
    {
        var publicTopic = await forumRepository.GetTopicPostsPageAsync(topicId, 1, 1, cancellationToken);
        if (publicTopic is null)
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.TopicNotFound);
        }

        var thread = await forumWriteRepository.GetThreadAsync(topicId, cancellationToken);
        if (thread is null)
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.TopicNotFound);
        }

        if (thread.IsLocked)
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.TopicLocked);
        }

        var author = await moderationService.ResolveAuthorAsync(memberId, identityName, cancellationToken);
        if (author.Status != ForumWriteStatus.Success)
        {
            return ForumWriteOutcome.Fail(author.Status);
        }

        var fieldErrors = new List<ForumWriteFieldError>();
        var sanitizedBody = contentService.NormalizeForStorage(body);
        if (string.IsNullOrWhiteSpace(sanitizedBody))
        {
            fieldErrors.Add(new ForumWriteFieldError("Body", BodyRequiredMessage));
        }

        var attachmentValidation = contentService.ValidateAttachments(attachments);
        foreach (var error in attachmentValidation.Errors)
        {
            fieldErrors.Add(new ForumWriteFieldError("Attachments", error));
        }

        if (fieldErrors.Count > 0)
        {
            return ForumWriteOutcome.Validation(sanitizedBody, fieldErrors);
        }

        if (!await rateLimiter.IsAllowedAsync(memberId, cancellationToken))
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.RateLimited, sanitizedBody);
        }

        var title = publicTopic.Header.Title;
        try
        {
            var createdAt = timeProvider.GetUtcNow();
            var postId = await forumWriteRepository.CreatePostAsync(
                new NewForumPost(
                    topicId,
                    memberId,
                    author.DisplayName,
                    sanitizedBody,
                    createdAt),
                cancellationToken);
            await writeEffects.UpsertThreadAsync(topicId, title, createdAt, cancellationToken);
            await contentService.UploadAttachmentsAsync(
                postId,
                memberId,
                attachmentValidation.AcceptedFiles,
                cancellationToken);
            writeEffects.InvalidateForumStatsCache();
            await FlagIfLikelySpamAsync(
                memberId, author.AccountCreatedAt, author.Email, createdAt, sanitizedBody, cancellationToken);
            var created = ForumWriteOutcome.Created(topicId, postId, sanitizedBody, title);
            await writeEffects.NotifyReplyAsync(topicId, postId, memberId, title, cancellationToken);

            return created;
        }
        catch (NotSupportedException ex)
        {
            return ForumWriteOutcome.AttachmentFailed(sanitizedBody, ex.Message);
        }
        catch (BlobUploadException ex)
        {
            return ForumWriteOutcome.AttachmentFailed(sanitizedBody, ex.Message);
        }
        catch (InvalidOperationException)
        {
            return ForumWriteOutcome.Fail(ForumWriteStatus.TopicNotFound, sanitizedBody);
        }
    }

    /// <summary>
    /// Auto-suspends and hides content matching the bulk-signup-bot signature: within
    /// <see cref="SpamCandidateWindow"/> of account creation, either a link is posted or the
    /// registration email itself matches <see cref="AutoGeneratedFreemailPattern"/> — the
    /// email shape alone is enough, since a genuine member never registers with one. Runs
    /// after a successful write so a false positive still leaves the post recoverable via
    /// admin reinstatement, the same recovery path as a manual suspension.
    /// </summary>
    private Task FlagIfLikelySpamAsync(
        Guid memberId, DateTime? accountCreatedAt, string? email, DateTimeOffset postedAt,
        string sanitizedBody, CancellationToken cancellationToken) =>
        moderationService.FlagIfLikelySpamAsync(
            memberId, accountCreatedAt, email, postedAt, sanitizedBody, cancellationToken);
}
