using System.Text.RegularExpressions;
using Microsoft.Extensions.Logging;
using QueenZone.Data;

namespace QueenZone.Web;

public sealed partial class ForumPostModerationService(
    MemberAccountService memberAccountService,
    IForumWriteRepository forumWriteRepository,
    TimeProvider timeProvider,
    ILogger<ForumPostWriteService> logger)
{
    private static readonly Regex UrlPattern = new(
        @"https?://|www\.",
        RegexOptions.IgnoreCase | RegexOptions.Compiled,
        RegexDefaults.MatchTimeout);

    public async Task<(ForumWriteStatus Status, string DisplayName, DateTime? AccountCreatedAt, string? Email)> ResolveAuthorAsync(
        Guid memberId,
        string? identityName,
        CancellationToken cancellationToken)
    {
        var account = await memberAccountService.FindByIdAsync(memberId, cancellationToken);
        if (account?.IsSuspended == true)
        {
            return (ForumWriteStatus.MemberSuspended, string.Empty, null, null);
        }

        if (!string.IsNullOrWhiteSpace(account?.DisplayName))
        {
            return (ForumWriteStatus.Success, account.DisplayName, account.CreatedAt, account.Email);
        }

        var fallback = string.IsNullOrWhiteSpace(identityName) ? "Member" : identityName;
        return (ForumWriteStatus.Success, fallback, account?.CreatedAt, account?.Email);
    }

    public async Task FlagIfLikelySpamAsync(
        Guid memberId,
        DateTime? accountCreatedAt,
        string? email,
        DateTimeOffset postedAt,
        string sanitizedBody,
        CancellationToken cancellationToken)
    {
        if (accountCreatedAt is null || postedAt.UtcDateTime - accountCreatedAt.Value > ForumPostWriteService.SpamCandidateWindow)
        {
            return;
        }

        var hasLink = UrlPattern.IsMatch(sanitizedBody);
        var hasAutoGeneratedEmail = !string.IsNullOrEmpty(email) && ForumPostWriteService.AutoGeneratedFreemailPattern.IsMatch(email);
        if (!hasLink && !hasAutoGeneratedEmail)
        {
            return;
        }

        var signature = (hasLink, hasAutoGeneratedEmail) switch
        {
            (true, true) => "a link and an auto-generated-looking registration email",
            (true, false) => "a link",
            _ => "an auto-generated-looking registration email",
        };
        var reason =
            $"Auto-flagged: posted with {signature} within {ForumPostWriteService.SpamCandidateWindow.TotalSeconds:0}s of registering "
            + "(matches automated bulk-signup pattern).";
        var suspended = await memberAccountService.SuspendAsync(
            memberId, reason, ForumPostWriteService.AutoModeratorEmail, timeProvider.GetUtcNow().UtcDateTime, cancellationToken);
        if (suspended is null)
        {
            return;
        }

        await forumWriteRepository.HideAuthorForumContentAsync(
            memberId, suspended.DisplayName, cancellationToken);
        Log.AutoSuspendedMember(
            logger,
            memberId,
            signature,
            (postedAt.UtcDateTime - accountCreatedAt.Value).TotalSeconds);
    }

}
